name: Realtime Development Stats

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 * * * *'

jobs:
  update-readme:
    - name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
       - uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE: "False"
          SHOW_LOC_CHART: "False"
        
